version: '3'
services:
  corb:
    build:
      context: gradle
      args:
        CORB_JAR_PATH: "${CORB_JAR_PATH}"
    container_name: corb
    image: gradle:ml${ML_VERSION}
    hostname: corb
    volumes:
      - "${LOCAL_VOLUME_DIR}/corb-${BUILD_ENV}:/corb"
  odh:
    build:
      context: gradle
      args:
        ODH_INSTALL_PATH: "${ODH_INSTALL_PATH}"
    container_name: odh
    hostname: odh
    image: gradle:ml${ML_VERSION}
    command: "java -jar /opt/odh/${ODH_INSTALL_PATH}"
    ports:
      - "${ODH_PORT}:8080"
    volumes:
      - "${LOCAL_VOLUME_DIR}/odh-${BUILD_ENV}:/odh"
  marklogic:
    build:
      context: "ml${ML_VERSION}"
      args:
        ML_INSTALL_PATH: "${ML_INSTALL_PATH}"
    image: "marklogic:marklogic${ML_VERSION}"
    container_name: "marklogic"
    hostname: marklogic
    volumes:
      - "${LOCAL_VOLUME_DIR}/marklogic${ML_VERSION}-${BUILD_ENV}-1:/var/opt/MarkLogic"
    ports:
      - "${ML_PORT_LOWER}-${ML_PORT_UPPER}:${ML_PORT_LOWER}-${ML_PORT_UPPER}"
    command: /bin/sh -c "/etc/init.d/MarkLogic start && tail -f /dev/null"
